name: "Tests"

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.1-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: fury_dumper_test
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      RAILS_ENV: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.1
      - name: Install dependencies
        run: bundle install
      - name: Test with RSpec
        env:
          RAILS_ENV: "test"
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: fury_dumper_test
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          RUBYOPT: "-W:no-deprecated -W:no-experimental"
        run: |
          bundle exec rake
      - name: Run rubocop
        run: bundle exec rubocop --display-cop-names
